"""Python code generation from GraphSchema."""

from __future__ import annotations

# Type → Python type name mapping
_TYPE_NAMES = {
    "string": "str",
    "number": "float",
    "boolean": "bool",
    "list": "list",
    "object": "dict",
}

# Type → default value repr
_DEFAULT_REPRS = {
    "string": '""',
    "number": "0.0",
    "boolean": "False",
    "list": "[]",
    "object": "{}",
}

# LLM provider → import line and class name
_PROVIDER_IMPORTS = {
    "openai": ("from langchain_openai import ChatOpenAI", "ChatOpenAI"),
    "anthropic": ("from langchain_anthropic import ChatAnthropic", "ChatAnthropic"),
    "gemini": (
        "from langchain_google_genai import ChatGoogleGenerativeAI",
        "ChatGoogleGenerativeAI",
    ),
}

# LLM provider → pip requirement
_PROVIDER_REQS = {
    "openai": "langchain-openai",
    "anthropic": "langchain-anthropic",
    "gemini": "langchain-google-genai",
}

# Tool name → pip requirements
_TOOL_REQS = {
    "calculator": ["simpleeval"],
    "url_fetch": ["httpx", "trafilatura"],
    "web_search": ["tavily-python", "duckduckgo-search"],
    "wikipedia": ["Wikipedia-API"],
    "weather": ["httpx"],
}


def export_graph(schema: dict) -> dict:
    """Generate standalone Python code from a GraphSchema.

    Returns:
        Dict with 'code' (Python source) and 'requirements' (pip requirements).
    """
    nodes = schema.get("nodes", [])
    edges = schema.get("edges", [])
    state_fields = schema.get("state", [])

    nodes_by_id = {n["id"]: n for n in nodes}
    start_id = next((n["id"] for n in nodes if n["type"] == "start"), None)
    end_ids = {n["id"] for n in nodes if n["type"] == "end"}

    # Collect what we need
    has_human_input = any(n["type"] == "human_input" for n in nodes)
    has_conditions = any(n["type"] == "condition" for n in nodes)
    has_merge_reducer = any(f.get("reducer") == "merge" for f in state_fields)
    has_append_messages = any(
        f.get("reducer") == "append" and f["key"] == "messages" for f in state_fields
    )
    has_append_other = any(
        f.get("reducer") == "append" and f["key"] != "messages" for f in state_fields
    )

    # Collect providers and tools
    providers = set()
    tool_names = set()
    for n in nodes:
        if n["type"] == "llm":
            providers.add(n["config"].get("provider", "openai"))
        if n["type"] == "tool":
            tool_names.add(n["config"].get("tool_name", ""))
        if n["type"] == "condition":
            cond = n["config"].get("condition", {})
            if cond.get("type") == "llm_router":
                providers.add("openai")  # default routing provider

    # Build condition edges
    condition_ids = {n["id"] for n in nodes if n["type"] == "condition"}
    cond_edges: dict[str, dict[str, str]] = {}
    normal_edges: list[dict] = []
    for edge in edges:
        if edge["source"] in condition_ids:
            branch = edge.get("condition_branch") or edge.get("label", "default")
            cond_edges.setdefault(edge["source"], {})[branch] = edge["target"]
        else:
            normal_edges.append(edge)

    # ── Generate code sections ──────────────────────────────────────────

    sections = []

    # 1. Docstring
    sections.append('"""Generated by GraphWeave — standalone LangGraph graph."""\n')

    # 2. Imports
    imports = _build_imports(
        providers,
        has_human_input,
        has_conditions,
        has_merge_reducer,
        has_append_messages,
        has_append_other,
    )
    sections.append(imports)

    # 3. Provider imports
    for provider in sorted(providers):
        if provider in _PROVIDER_IMPORTS:
            sections.append(_PROVIDER_IMPORTS[provider][0])
    sections.append("")

    # 4. Merge reducer (if needed)
    if has_merge_reducer:
        sections.append(_merge_reducer_code())

    # 5. State class
    sections.append(_build_state_class(state_fields))

    # 6. Node functions
    for n in nodes:
        if n["type"] in ("start", "end"):
            continue
        fn = _build_node_function(n, nodes_by_id)
        if fn:
            sections.append(fn)

    # 7. Condition routers
    for cond_id in sorted(cond_edges.keys()):
        cond_node = nodes_by_id[cond_id]
        router_fn = _build_router_function(cond_node, nodes_by_id, edges)
        if router_fn:
            sections.append(router_fn)

    # 8. Graph construction
    sections.append(
        _build_graph_construction(
            nodes,
            normal_edges,
            cond_edges,
            nodes_by_id,
            start_id,
            end_ids,
            has_human_input,
        )
    )

    # 9. Main block
    sections.append(_build_main_block(state_fields))

    code = "\n\n".join(s for s in sections if s)

    # ── Requirements ────────────────────────────────────────────────────
    reqs = _build_requirements(providers, tool_names)

    return {"code": code, "requirements": reqs}


def _build_imports(
    providers: set,
    has_human_input: bool,
    has_conditions: bool,
    has_merge_reducer: bool,
    has_append_messages: bool,
    has_append_other: bool,
) -> str:
    lines = []

    needs_operator = has_append_other
    needs_annotated = has_append_messages or has_append_other or has_merge_reducer

    if needs_operator:
        lines.append("import operator")

    typing_imports = ["TypedDict"]
    if needs_annotated:
        typing_imports.insert(0, "Annotated")
    lines.append(f"from typing import {', '.join(typing_imports)}")

    lg_imports = ["END", "START", "StateGraph"]
    lines.append(f"from langgraph.graph import {', '.join(lg_imports)}")

    if has_human_input:
        lines.append("from langgraph.types import interrupt")
        lines.append("from langgraph.checkpoint.memory import InMemorySaver")

    if has_append_messages:
        lines.append("from langgraph.graph.message import add_messages")

    if has_conditions:
        pass  # No extra imports needed for conditions

    return "\n".join(lines)


def _merge_reducer_code() -> str:
    return '''def _merge_reducer(left: dict, right: dict) -> dict:
    """Deep-merge two dicts."""
    result = {**left}
    for key, value in right.items():
        if key in result and isinstance(result[key], dict) and isinstance(value, dict):
            result[key] = _merge_reducer(result[key], value)
        else:
            result[key] = value
    return result'''


def _build_state_class(state_fields: list[dict]) -> str:
    lines = ["class GraphState(TypedDict):"]
    if not state_fields:
        lines.append("    pass")
        return "\n".join(lines)

    for f in state_fields:
        annotation = _field_annotation(f)
        lines.append(f"    {f['key']}: {annotation}")

    return "\n".join(lines)


def _field_annotation(field: dict) -> str:
    base = _TYPE_NAMES.get(field["type"], "str")
    reducer = field.get("reducer", "replace")

    if reducer == "replace":
        return base
    if reducer == "append":
        if field["key"] == "messages":
            return "Annotated[list, add_messages]"
        return "Annotated[list, operator.add]"
    if reducer == "merge":
        return "Annotated[dict, _merge_reducer]"
    return base


def _build_node_function(node: dict, nodes_by_id: dict) -> str:
    ntype = node["type"]
    nid = node["id"]
    config = node.get("config", {})

    if ntype == "llm":
        return _build_llm_function(nid, config)
    if ntype == "tool":
        return _build_tool_function(nid, config)
    if ntype == "condition":
        return _build_condition_passthrough(nid)
    if ntype == "human_input":
        return _build_human_function(nid, config)
    return ""


def _build_llm_function(node_id: str, config: dict) -> str:
    provider = config.get("provider", "openai")
    model = config.get("model", "gpt-4o")
    _, cls_name = _PROVIDER_IMPORTS.get(provider, _PROVIDER_IMPORTS["openai"])
    temp = config.get("temperature", 0.7)
    max_tokens = config.get("max_tokens", 1024)
    output_key = config.get("output_key", "result")
    system_prompt = config.get("system_prompt", "")
    input_map = config.get("input_map", {})

    lines = [f"async def {node_id}(state: GraphState) -> dict:"]

    # Build messages
    lines.append("    from langchain_core.messages import HumanMessage, SystemMessage")
    lines.append(
        f'    llm = {cls_name}(model="{model}", '
        f"temperature={temp}, max_tokens={max_tokens})"
    )
    lines.append("    messages = []")

    if system_prompt:
        lines.append(
            f'    messages.append(SystemMessage(content="{_escape(system_prompt)}"))'
        )

    # Input map
    if input_map:
        parts = []
        for key, expr in input_map.items():
            parts.append(f'"{key}: " + str(state.get("{expr}", ""))')
        user_content = ' + "\\n" + '.join(parts)
        lines.append(f"    messages.append(HumanMessage(content={user_content}))")
    else:
        lines.append("    messages.append(HumanMessage(content=str(state)))")

    lines.append("    response = await llm.ainvoke(messages)")
    lines.append(f'    return {{"{output_key}": response.content}}')

    return "\n".join(lines)


def _build_tool_function(node_id: str, config: dict) -> str:
    tool_name = config.get("tool_name", "unknown")
    output_key = config.get("output_key", "result")
    input_map = config.get("input_map", {})

    lines = [f"def {node_id}(state: GraphState) -> dict:"]
    lines.append(f'    """Run the {tool_name} tool."""')

    # Resolve inputs
    if input_map:
        lines.append("    inputs = {")
        for key, expr in input_map.items():
            lines.append(f'        "{key}": state.get("{expr}", ""),')
        lines.append("    }")
    else:
        lines.append("    inputs = {}")

    lines.append(f"    # TODO: Replace with actual {tool_name} tool call")
    lines.append('    result = {"success": True, "result": str(inputs)}')
    lines.append(f'    return {{"{output_key}": result}}')

    return "\n".join(lines)


def _build_condition_passthrough(node_id: str) -> str:
    return f"def {node_id}(state: GraphState) -> dict:\n    return {{}}"


def _build_human_function(node_id: str, config: dict) -> str:
    prompt = _escape(config.get("prompt", ""))
    input_key = config.get("input_key", "input")

    lines = [f"def {node_id}(state: GraphState) -> dict:"]
    lines.append(
        f'    value = interrupt({{"prompt": "{prompt}", '
        f'"input_key": "{input_key}", "node_id": "{node_id}"}})'
    )
    lines.append(f'    return {{"{input_key}": value}}')

    return "\n".join(lines)


def _build_router_function(
    cond_node: dict,
    nodes_by_id: dict,
    edges: list[dict],
) -> str:
    node_id = cond_node["id"]
    config = cond_node.get("config", {})
    condition = config.get("condition", {})
    ctype = condition.get("type", "field_equals")
    default = config.get("default_branch", "")

    lines = [f"def route_{node_id}(state: GraphState) -> str:"]

    if ctype == "field_equals":
        field = condition.get("field", "")
        value = condition.get("value", "")
        branch = condition.get("branch", "")
        lines.append(f'    if state.get("{field}") == "{value}":')
        lines.append(f'        return "{branch}"')
        lines.append(f'    return "{default}"')

    elif ctype == "field_contains":
        field = condition.get("field", "")
        value = condition.get("value", "")
        branch = condition.get("branch", "")
        lines.append(f'    if "{value}" in str(state.get("{field}", "")):')
        lines.append(f'        return "{branch}"')
        lines.append(f'    return "{default}"')

    elif ctype == "field_exists":
        field = condition.get("field", "")
        branch = condition.get("branch", "")
        lines.append(f'    if "{field}" in state and state["{field}"] is not None:')
        lines.append(f'        return "{branch}"')
        lines.append(f'    return "{default}"')

    elif ctype == "tool_error":
        # Find source tool's output_key
        tool_key = _find_tool_output_key_for_export(cond_node["id"], nodes_by_id, edges)
        on_success = condition.get("on_success", "")
        on_error = condition.get("on_error", "")
        lines.append(f'    tool_output = state.get("{tool_key}", {{}})')
        lines.append(
            '    if isinstance(tool_output, dict) and tool_output.get("success"):'
        )
        lines.append(f'        return "{on_success}"')
        lines.append(f'    return "{on_error}"')

    elif ctype == "iteration_limit":
        field = condition.get("field", "counter")
        max_val = condition.get("max", 3)
        exceeded = condition.get("exceeded", "end")
        cont = condition.get("continue", "continue")
        lines.append(f'    if state.get("{field}", 0) >= {max_val}:')
        lines.append(f'        return "{exceeded}"')
        lines.append(f'    return "{cont}"')

    elif ctype == "llm_router":
        lines.append("    # TODO: Implement LLM routing logic")
        lines.append(f'    return "{default}"')

    else:
        lines.append(f'    return "{default}"')

    return "\n".join(lines)


def _find_tool_output_key_for_export(
    cond_id: str, nodes_by_id: dict, edges: list[dict]
) -> str:
    """Find the output_key of the tool node that feeds into a condition."""
    for edge in edges:
        if edge["target"] == cond_id:
            source = nodes_by_id.get(edge["source"])
            if source and source["type"] == "tool":
                return source["config"].get("output_key", "result")
    return "result"


def _build_graph_construction(
    nodes: list[dict],
    normal_edges: list[dict],
    cond_edges: dict[str, dict[str, str]],
    nodes_by_id: dict,
    start_id: str | None,
    end_ids: set[str],
    has_human_input: bool,
) -> str:
    lines = ["# Build graph", "graph = StateGraph(GraphState)"]

    # Add nodes
    for n in nodes:
        if n["type"] in ("start", "end"):
            continue
        lines.append(f'graph.add_node("{n["id"]}", {n["id"]})')

    lines.append("")

    # Add normal edges
    for edge in normal_edges:
        source = "START" if edge["source"] == start_id else f'"{edge["source"]}"'
        target = "END" if edge["target"] in end_ids else f'"{edge["target"]}"'
        lines.append(f"graph.add_edge({source}, {target})")

    # Add conditional edges
    for cond_id, branch_map in sorted(cond_edges.items()):
        translated = {}
        for branch, target in branch_map.items():
            translated[branch] = "END" if target in end_ids else target
        branch_repr = "{\n"
        for branch, target in sorted(translated.items()):
            target_val = "END" if target == "END" else f'"{target}"'
            branch_repr += f'    "{branch}": {target_val},\n'
        branch_repr += "}"
        lines.append(
            f'graph.add_conditional_edges("{cond_id}", route_{cond_id}, {branch_repr})'
        )

    lines.append("")

    # Compile
    if has_human_input:
        lines.append("# Human input nodes require a checkpointer")
        lines.append("compiled = graph.compile(checkpointer=InMemorySaver())")
    else:
        lines.append("compiled = graph.compile()")

    return "\n".join(lines)


def _build_main_block(state_fields: list[dict]) -> str:
    defaults = {}
    for f in state_fields:
        if "default" in f and f["default"] is not None:
            defaults[f["key"]] = f["default"]
        else:
            defaults[f["key"]] = _python_default(f["type"])

    defaults_repr = "{\n"
    for key, val in defaults.items():
        defaults_repr += f'    "{key}": {repr(val)},\n'
    defaults_repr += "}"

    return f"""if __name__ == "__main__":
    import asyncio

    result = asyncio.run(compiled.ainvoke({defaults_repr}))
    print(result)"""


def _python_default(type_name: str) -> object:
    return {"string": "", "number": 0.0, "boolean": False, "list": [], "object": {}}[
        type_name
    ]


def _escape(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")


def _build_requirements(providers: set, tool_names: set) -> str:
    reqs = {"langgraph", "langchain-core"}
    for p in providers:
        if p in _PROVIDER_REQS:
            reqs.add(_PROVIDER_REQS[p])
    for t in tool_names:
        for r in _TOOL_REQS.get(t, []):
            reqs.add(r)
    return "\n".join(sorted(reqs))
