"""Python code generation from GraphSchema."""


def export_graph(schema: dict) -> dict:
    """Generate standalone Python code from a GraphSchema.

    Args:
        schema: A GraphSchema dictionary.

    Returns:
        Dict with 'code' (Python source) and 'requirements' (requirements.txt content).
    """
    # TODO: Implement code generation
    return {
        "code": "# Generated by GraphWeave\n# TODO: implement\n",
        "requirements": "langgraph\nlangchain-openai\n",
    }
